type: app
description: Basic nextjs app with turborepo
# template used to create the project
template: orgs-matter-web-nextjs/app-shell
# inputs:
#   some_input: value
# list of plugins to be applied after project creation
# plugins:
#   - plugin: orgs-matter-web-nextjs/<plugin-name>
#     inputs:
#       some_input: value
#       some_list:
#         - item1
#         - item2
