name: uxservices-web-nextjs-template
description: Boilerplate NextJS
types:
  - app-template
inputs:
  - label: "Project name(must not have spaces and be lowercase)"
    type: text
    name: project_name
    default: myapp
