description: NextJs stack
name: orgs-matter-web-nextjs
display-name: orgs-matter-web-nextjs
picture: stack.png
category: Front-end
technologies:
  - Typescript
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml
