description: Next.js stack para aplicações multizonas com monorepo utilizando o turbo
name: matter-web-nextjs
display-name: matter-web-nextjs
picture: NextJsLogo.jpg
category: Frontend
technologies:
  - Typescript
about: docs/about.md
use-cases:
  - title: Criar aplicação Next.js com turbo
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml
